### ISSUE TITLE
Error on fresh install

### ISSUE THREAD

**Issue by tim427** [ccryx/python-keephasshttpc#4]
Hi @ccryx ,

I tried your "python-keephasshttpc", but everytime I launch the python script, I receive the following error:

> tim427@test01:~$ python3.5 ./keepasshttpc.py associate
> Traceback (most recent call last):
>   File "./keepasshttpc.py", line 113, in <module>
>     args.func(args)
>   File "./keepasshttpc.py", line 82, in <lambda>
>     lambda args: print(associate(args.unlock)))
> TypeError: associate() takes 0 positional arguments but 1 was given

Any ideas?

**Comment by ccryx** [comment]
Hi @tim427 , it seems I messed up at some point after associating with my keepasshttp server.
I'll push the fix in a few minutes.
FYI, I've since moved to using pgp and pass myself, so I will probably not invest that much time in this project in the future.
